name: base
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: base

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v3
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community

      - name: Prepare Workstation
        shell: bash
        run: |
          wget `curl -s https://api.github.com/repos/zhanhb/cidr-merger/releases/latest | grep -Po '(?<=download_url\"\: \").*linux-amd64'`
          mv cidr-merger-linux-amd64 cidr-merger
          chmod +x cidr-merger

      - name: Run
        run: |
          mkdir master
          curl -sSL https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%204/Head.conf > Head.conf
          curl -sSL https://raw.githubusercontent.com/TomKing062/Shadowrocket/main/Rule.conf > Rule.conf
          curl -sSL https://raw.githubusercontent.com/TomKing062/Shadowrocket/main/Rule-edu.conf > Rule-edu.conf
          curl -sSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising_MITM.sgmodule > MITM.conf
          curl -sSL https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list | grep bili > master/Streaming.list
          
          curl -sSL https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt | sed '/^\#/d' > ipv4-1.txt
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt > ipv4-2.txt
          curl -sSL https://raw.githubusercontent.com/felixonmars/chnroutes-alike/master/chnroutes-alike.txt | sed '/^\#/d' > ipv4-3.txt
          cat ipv4*.txt | ./cidr-merger -s | perl -ne '/^(\d{1,3}(\.\d{1,3}){3}\/\d{1,2})/ && print "IP-CIDR,$1\n"' > master/directcidr.txt
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' >> master/directcidr.txt
          cat Head.conf Rule.conf MITM.conf > master/Shadowrocket.conf
          sed -i "/test/d" master/Shadowrocket.conf
          sed -i "/#/d" master/Shadowrocket.conf
          
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/cernet.txt | perl -ne '/^(\d{1,3}(\.\d{1,3}){3}\/\d{1,2})/ && print "IP-CIDR,$1\n"' > master/educidr.txt
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/cernet6.txt | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' >> master/educidr.txt
          cat Head.conf Rule-edu.conf > master/Edu.conf
          sed -i "/test/d" master/Edu.conf
          sed -i "/#/d" master/Edu.conf
          
          cd domain-list-community
          go run ./ --exportlists=google-ads
          cat google-ads.txt | grep -E "^domain:" | awk -F ':' '{printf "DOMAIN-SUFFIX,%s\n", $2}' > ../master/google-ads.list

      - name: push
        run: |
          cd master
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git init
          git checkout -b master
          git add .
          git commit -m "Base $(TZ='Asia/Shanghai' date +%Y%m%d)"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin master
