name: Shadowrocket
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 4"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v5
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community

      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master
          path: master

      - name: Prepare Workstation
        shell: bash
        run: |
          wget `curl -s https://api.github.com/repos/zhanhb/cidr-merger/releases/latest | grep -Po '(?<=download_url\"\: \").*linux-amd64'`
          mv cidr-merger-linux-amd64 cidr-merger
          chmod +x cidr-merger

      - name: Run
        run: |
          rm master/*
          curl -sSL https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%204/Head.conf > Head.conf
          curl -sSL https://raw.githubusercontent.com/TomKing062/Shadowrocket/main/Rule.conf > Rule.conf
          curl -sSL https://raw.githubusercontent.com/TomKing062/Shadowrocket/main/Rule-blacklist.conf > Rule-blacklist.conf
          curl -sSL https://raw.githubusercontent.com/TomKing062/Shadowrocket/main/Rule-edu.conf > Rule-edu.conf
          curl -sSL https://raw.githubusercontent.com/TomKing062/Shadowrocket/main/Streaming.list > master/Streaming.list
          curl -sSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising_MITM.sgmodule > MITM.conf
          sed -i "/generate/d" Head.conf
          echo "" >> Head.conf
          
          curl -sSL https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt > ipv4-1.txt
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt > ipv4-2.txt
          curl -sSL https://raw.githubusercontent.com/felixonmars/chnroutes-alike/master/chnroutes-alike.txt > ipv4-3.txt
          cat ipv4*.txt | ./cidr-merger -s | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' > master/directcidr.txt
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' >> master/directcidr.txt
          cat Head.conf Rule.conf MITM.conf > master/Shadowrocket.conf
          sed -i "/#/d" master/Shadowrocket.conf
          
          curl -sSL https://raw.githubusercontent.com/Johnshall/cn-blocked-domain/release/domains.txt | perl -ne '/(.+\..+)/ && print "DOMAIN-SUFFIX,$1\n"' > master/greatfire.list
          curl -sSL https://raw.githubusercontent.com/Johnshall/cn-blocked-domain/release/ip.txt | ./cidr-merger -s | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' > master/gfwcidr.txt
          curl -sSL https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' > master/tgcidr.txt
          cat Head.conf Rule-blacklist.conf MITM.conf > master/Blacklist.conf
          sed -i "/#/d" master/Blacklist.conf
          
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/cernet.txt | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' > master/educidr.txt
          curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/cernet6.txt | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1\n"' >> master/educidr.txt
          cat Head.conf Rule-edu.conf > master/Edu.conf
          sed -i "/#/d" master/Edu.conf
          
          cd domain-list-community
          echo "include:category-education-cn" > data/scholar
          echo "include:category-mooc-cn" >> data/scholar
          echo "include:category-scholar-!cn" >> data/scholar
          echo "include:category-scholar-cn" >> data/scholar
          go run ./ --exportlists=google-ads,google,scholar
          cat google-ads.txt | grep -E "^domain:" | awk -F ':' '{printf "DOMAIN-SUFFIX,%s\n", $2}' > ../master/google-ads.list
          cat google.txt | grep -E "^full:" | awk -F ':' '{printf "DOMAIN,%s\n", $2}' > ../master/google.list
          cat google.txt | grep -E "^domain:" | awk -F ':' '{printf "DOMAIN-SUFFIX,%s\n", $2}' >> ../master/google.list
          cat scholar.txt | grep -E "^full:" | awk -F ':' '{printf "DOMAIN,%s\n", $2}' > ../master/scholar.list
          cat scholar.txt | grep -E "^domain:" | awk -F ':' '{printf "DOMAIN-SUFFIX,%s\n", $2}' >> ../master/scholar.list

      - name: push
        run: |
          cd master
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Uploaded on $(TZ='Asia/Shanghai' date +%Y%m%d%H%M)"
          git push
